# Generated by Django 5.0.6 on 2024-06-25 15:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='coment',
            field=ckeditor.fields.RichTextField(verbose_name='Comentario'),
        ),
    ]
